Repository uhmanoalink/manoa-link, pull requests merged in 2023-04, with the labels that each got.

#18 17 setup ci tests and lint check
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/eslint.yml
  .github/workflows/testcafe.yml
  .gitignore
  app/imports/api/company/Company.js
  app/imports/api/event/Event.js
  app/imports/api/position/Position.js
  app/imports/api/user/User.js
  app/imports/ui/pages/Landing.jsx
  app/package.json
  app/tests/landing.page.ts
  app/tests/tests.testcafe.js
  app/tests/tests.testcafe.ts
  tsconfig.json
Labels: final review

#25 Move pull_request_template.md to .github
  .github/pull_request_template.md
Labels: final review

#27 26 update readme
  README.md
Labels: final review

#38 Fix meteor scss error
  app/.meteor/packages
  app/.meteor/release
  app/.meteor/versions
  app/client/main.js
  app/client/style.css
  app/client/style.css.map
  app/package-lock.json
  app/package.json
Labels: final review

#40 Added routes & NavBar Links, tests, script edit
  app/imports/ui/components/NavBar.jsx
  app/imports/ui/layouts/App.jsx
  app/imports/ui/pages/AddEvents.jsx
  app/imports/ui/pages/CompanyListing.jsx
  app/imports/ui/pages/ListEvents.jsx
  app/imports/ui/pages/MyProfile.jsx
  app/package.json
  app/tests/addevents.page.ts
  app/tests/companylisting.page.ts
  app/tests/listevents.page.ts
  app/tests/myprofile.page.ts
  app/tests/navbar.component.ts
  app/tests/signin.page.ts
  app/tests/signout.page.ts
  app/tests/signup.page.ts
  app/tests/tests.testcafe.ts
Labels: final review

#35 33 refactor appjsx
  .github/workflows/testcafe.yml
  app/imports/ui/layouts/AdminProtectedRoute.jsx
  app/imports/ui/layouts/App.jsx
  app/imports/ui/layouts/ProtectedRoute.jsx
  app/package.json
Labels: final review

#39 34 add and configure typescript eslint package
  .github/workflows/eslint.yml
  app/.eslintrc.js
  app/package-lock.json
  app/package.json
  app/tests/landing.page.ts
  app/tests/signin.component.ts
  app/tests/tests.testcafe.ts
Labels: final review, blocked

#43 deploy for final project
  config/settings.development.json
Labels: final review

#49 add install meteor
  .github/workflows/deploy.yml
Labels: final review

#51 Fix deployment workflow
  .github/workflows/deploy.yml
Labels: final review

#48 Company Listing Page Mockup
  app/imports/startup/server/Accounts.js
  app/imports/ui/components/NavBar.jsx
  app/imports/ui/layouts/App.jsx
  app/imports/ui/layouts/CompanyProtectedRoute.jsx
  app/imports/ui/layouts/UserProtectedRoute.jsx
  app/package-lock.json
  app/tests/addevents.page.ts
  app/tests/companylisting.page.ts
  app/tests/listevents.page.ts
  app/tests/myprofile.page.ts
  app/tests/signin.page.ts
  app/tests/signout.page.ts
  app/tests/signup.page.ts
  app/tests/tests.testcafe.ts
  config/settings.development.json
Labels: work in progress

#54 fix-deployment-workflow - back to global mup install
  .github/workflows/deploy.yml
Labels: final review

#55 fix-deployment-workflow - wrap mup.js content in single quotes instead of double quotes
  .github/workflows/deploy.yml
Labels: final review

#60 Made Company Listing Mockup
  app/client/scss/_company-listing.scss
  app/client/style.css
  app/client/style.css.map
  app/client/style.scss
  app/imports/ui/pages/CompanyListing.jsx
Labels: final review

#63 45 my profile mockup
  app/client/scss/_my-profile.scss
  app/client/style.css
  app/client/style.css.map
  app/client/style.scss
  app/imports/ui/pages/MyProfile.jsx
  app/public/images/sample-pfp.png
Labels: final review

#57 56 update footer
  .gitignore
  app/client/scss/_components.scss
  app/client/scss/_typography.scss
  app/client/style.css
  app/client/style.scss
  app/imports/ui/components/Footer.jsx
  app/tests/footer.component.ts
  app/tests/tests.testcafe.ts
Labels: final review

#71 Delete style.css
  app/client/style.css
  app/client/style.css.map
Labels: final review

#73 Add build step to deployment
  .github/workflows/deploy.yml
Labels: final review

#75 add build script and update workflows
  .github/workflows/deploy.yml
  .github/workflows/testcafe.yml
  app/package.json
Labels: final review

#76 58 update landing page
  app/client/scss/_landing.scss
  app/client/scss/components/__components.scss
  app/client/scss/components/_footer.scss
  app/client/scss/components/_signin.scss
  app/client/scss/globals/__globals.scss
  app/client/scss/globals/_colors.scss
  app/client/scss/globals/_typography.scss
  app/client/scss/pages/__pages.scss
  app/client/scss/pages/_company-listing.scss
  app/client/scss/pages/_dashboard.scss
  app/client/scss/pages/_landing.scss
  app/client/scss/pages/_my-profile.scss
  app/client/style.scss
  app/imports/ui/components/SignIn.jsx
  app/imports/ui/pages/Landing.jsx
  app/public/images/networking.jpg
  app/tests/landing.page.ts
  app/tsconfig.json
Labels: final review

#42 24 make components files for studnet company event position
  app/imports/api/company/Company.js
  app/imports/api/event/Event.js
  app/imports/api/position/Position.js
  app/imports/ui/components/Company.jsx
  app/imports/ui/components/Event.jsx
  app/imports/ui/components/Position.jsx
  app/imports/ui/components/User.jsx
Labels: final review

#72 Done - 32 - user -dashboard-mockup-page
  app/client/scss/pages/__pages.scss
  app/client/scss/pages/_company-dashboard.scss
  app/client/scss/pages/_student-dashboard.scss
  app/imports/api/company/Company.js
  app/imports/startup/server/Mongo.js
  app/imports/startup/server/Publications.js
  app/imports/ui/components/NavBar.jsx
  app/imports/ui/components/SignIn.jsx
  app/imports/ui/layouts/App.jsx
  app/imports/ui/pages/CompanyListing.jsx
  app/imports/ui/pages/Dashboard.jsx
  app/imports/ui/pages/Landing.jsx
  app/imports/ui/pages/StudentDashboard.jsx
  app/package-lock.json
  app/tests/dashboard.page.ts
  app/tests/navbar.component.ts
  app/tests/signin.component.ts
Labels: final review

#95 69 redesign navbar
  app/client/main.html
  app/client/scss/components/__components.scss
  app/client/scss/components/_navbar.scss
  app/client/scss/globals/__globals.scss
  app/client/scss/globals/_colors.scss
  app/client/scss/globals/_typography.scss
  app/client/scss/globals/_variables.scss
  app/client/scss/pages/_my-profile.scss
  app/imports/ui/components/NavBar.jsx
  app/imports/ui/components/ProtectedRender.jsx
  app/imports/ui/layouts/App.jsx
  app/imports/ui/pages/SignOut.jsx
  app/package-lock.json
  app/package.json
  app/public/images/logo.png
  app/tests/dashboard.page.ts
  app/tests/navbar.component.ts
  app/tests/tests.testcafe.ts
Labels: final review

#97 96 small tasks
  app/imports/ui/components/Footer.jsx
  app/public/favicon.ico
Labels: enhancement, final review

#93 Added roles to registration
  app/imports/startup/server/Accounts.js
  app/imports/startup/server/Mongo.js
  app/imports/ui/pages/Dashboard.jsx
  app/imports/ui/pages/SignIn.jsx
  app/imports/ui/pages/SignOut.jsx
  app/imports/ui/pages/SignUp.jsx
  app/package-lock.json
  config/settings.development.json
Labels: final review

#92 52 form schema and implement submit function for edit and add pages
  app/imports/api/company/Company.js
  app/imports/ui/layouts/App.jsx
  app/imports/ui/pages/AddEvent.jsx
  app/imports/ui/pages/AddEvents.jsx
  app/imports/ui/pages/EditEvent.jsx
  app/imports/ui/pages/ListEvents.jsx
Labels: final review

#103 74 implement list-events, add-event, edit-event
  app/client/scss/components/__components.scss
  app/client/scss/components/_event-card.scss
  app/imports/api/event/Event.js
  app/imports/startup/server/Mongo.js
  app/imports/ui/components/Event.jsx
  app/imports/ui/layouts/App.jsx
  app/imports/ui/pages/AddEvent.jsx
  app/imports/ui/pages/EditEvent.jsx
  app/imports/ui/pages/ListEvents.jsx
  app/package-lock.json
  app/package.json
  config/settings.development.json
Labels: final review

#104 99 fix registration roles
  app/client/main.js
  app/imports/startup/both/Methods.js
  app/imports/ui/pages/SignUp.jsx
  app/server/main.js
  app/tests/navbar.component.ts
  app/tests/signup.page.ts
  app/tests/tests.testcafe.ts
  app/tests/types/RoleType.ts
Labels: final review

#106 82 link the about us blog and faq page in footer
  app/imports/ui/components/Footer.jsx
  app/tests/footer.component.ts
Labels: final review

#102 84 re style landing page and my profile
  app/.unimportedrc.json
  app/client/scss/components/_footer.scss
  app/client/scss/components/_signin.scss
  app/client/scss/globals/_typography.scss
  app/client/scss/pages/_landing.scss
  app/imports/ui/components/LandingCarousel.jsx
  app/imports/ui/components/SignIn.jsx
  app/imports/ui/pages/SignUp.jsx
  app/public/fonts/zero-hour.otf
  app/public/images/honolulu.jpeg
  app/public/images/logo-black.PNG
  app/public/images/manoa.jpg
  app/public/images/oahu.jpeg
  app/public/images/seemoo-Manoa.PNG
Labels: final review

#113 112 create company profile page
  app/client/scss/globals/_colors.scss
  app/client/scss/globals/_utilities.scss
  app/client/scss/pages/_my-profile.scss
  app/imports/ui/layouts/App.jsx
  app/imports/ui/pages/CompanyProfile.jsx
  app/imports/ui/pages/Profile.jsx
  app/imports/ui/pages/StudentProfile.jsx
  app/tests/companyprofile.page.ts
  app/tests/myprofile.page.ts
  app/tests/studentprofile.page.ts
  app/tests/tests.testcafe.ts
Labels: final review

#111 96 small tasks
  _config.yml
  app/client/scss/components/_signin.scss
  app/client/scss/globals/_utilities.scss
  app/client/scss/pages/_landing.scss
  app/client/scss/pages/_student-dashboard.scss
  app/imports/ui/components/AddToCalendarDropdown.jsx
  app/imports/ui/components/NavBar.jsx
  app/imports/ui/components/ProtectedRender.jsx
  app/imports/ui/components/SignIn.jsx
  app/imports/ui/pages/SignIn.jsx
  app/imports/ui/pages/StudentDashboard.jsx
  doc/add-stuff-page.png
  doc/admin-landing-page.png
  doc/admin-list-stuff-page.png
  doc/edit-stuff-page.png
  doc/landing-after-login-page.png
  doc/landing-page.png
  doc/list-stuff-page.png
  doc/meteor-application-template-react-youtube.png
  doc/meteor-application-template-youtube.png
  doc/not-authorized-page.png
  doc/register-page.png
  doc/signin-page.png
  index.md
Labels: enhancement, final review

#114 89 complete company dashboard page
  app/client/scss/pages/_company-dashboard.scss
  app/imports/ui/pages/CompanyDashboard.jsx
  app/package-lock.json
  app/package.json
  app/tests/companydashboard.page.ts
Labels: final review

#124 clean up methods
  app/imports/startup/both/Methods.js
  app/imports/ui/pages/SignUp.jsx
Labels: final review

#119 Fixed for MainEvents, Company, etc.
  app/imports/ui/components/Company.jsx
  app/imports/ui/components/Event.jsx
  app/imports/ui/components/NavBar.jsx
  app/imports/ui/layouts/App.jsx
  app/imports/ui/pages/ListEvents.jsx
  app/imports/ui/pages/ListStuffAdmin.jsx
  app/imports/ui/pages/MainEventsList.jsx
  app/package-lock.json
  app/tests/navbar.component.ts
Labels: final review

#135 131 fix failing events page tests
  app/imports/api/event/Event.js
  app/imports/api/listing/Listing.js
  app/imports/ui/pages/MainEventsList.jsx
Labels: bug, final review

#125 120 upload and save files to mongo
  app/.meteor/packages
  app/.meteor/versions
  app/client/scss/components/__components.scss
  app/client/scss/components/_file-upload.scss
  app/imports/api/image/Image.js
  app/imports/api/image/files/createInterceptDownload.js
  app/imports/api/image/files/createOnAfterRemove.js
  app/imports/api/image/files/createOnAfterUpload.js
  app/imports/api/image/grid/createBucket.js
  app/imports/api/image/grid/createObjectId.js
  app/imports/startup/server/Publications.js
  app/imports/ui/components/FileUpload.jsx
Labels: final review

#134 132 listing collection, job listing page, restyling
  app/client/scss/pages/__pages.scss
  app/client/scss/pages/_listing.scss
  app/imports/api/listing/Listing.js
  app/imports/ui/components/NavBar.jsx
  app/imports/ui/layouts/App.jsx
  app/imports/ui/pages/CompanyListing.jsx
  app/imports/ui/pages/JobListing.jsx
  app/tests/navbar.component.ts
Labels: final review

#130 127 finish sign up sequence
  app/client/scss/components/__components.scss
  app/client/scss/components/_sign-up.scss
  app/imports/api/company/Company.js
  app/imports/api/event/Event.js
  app/imports/api/image/Image.js
  app/imports/api/listing/Listing.js
  app/imports/api/student/Student.js
  app/imports/startup/both/Methods.js
  app/imports/ui/components/CompanySignUpForm.jsx
  app/imports/ui/components/FileUpload.jsx
  app/imports/ui/components/Footer.jsx
  app/imports/ui/components/RegisterUserForm.jsx
  app/imports/ui/components/StudentSignUpForm.jsx
  app/imports/ui/pages/SignUp.jsx
  app/lib/files.js
  app/package-lock.json
  app/package.json
  app/public/images/sample-company-pfp.png
  app/tests/signup.page.ts
  app/tests/types/DocumentSchemas.ts
  app/tests/types/RegisterCompanyInputDataType.ts
  app/tests/types/RegisterStudentInputDataType.ts
  config/settings.development.json
Labels: final review
